services:
  db:
    image: postgres:16
    container_name: qundylyk-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"


  web:
    build: .
    container_name: qundylyk-django
    restart: unless-stopped
    env_file:
      - .env
    command: >
      sh -c "
      cd backend &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/app
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:latest
    container_name: qundylyk-ngrok
    restart: unless-stopped
    env_file:
      - .env
    command: ["http", "web:8000"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
