services:
  db:
    image: postgres:16
    container_name: qundylyk-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"


  web:
    build: .
    container_name: qundylyk-django
    restart: unless-stopped
    env_file:
      - .env
    command: >
      sh -c "
      cd backend &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn qundylyq_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
      "
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2
    container_name: qundylyk-caddy
    restart: unless-stopped
    profiles: ["duckdns"]
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/srv/static
      - media_volume:/srv/media
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: qundylyk-duckdns
    restart: unless-stopped
    profiles: ["duckdns"]
    env_file:
      - .env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true
    volumes:
      - duckdns_config:/config

  ngrok:
    image: ngrok/ngrok:latest
    container_name: qundylyk-ngrok
    restart: unless-stopped
    env_file:
      - .env
    command: ["http", "web:8000"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:
  duckdns_config:
