# Generated by Django 6.0.1 on 2026-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып / Заголовок')),
                ('description', models.TextField(verbose_name='Сипаттама / Описание')),
                ('image', models.ImageField(upload_to='blocks/', verbose_name='Сурет / Изображение')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег / Тэг')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сілтеме / Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік нөмірі / Порядок')),
            ],
            options={
                'verbose_name': 'Фото блок',
                'verbose_name_plural': 'Фото блоктар',
                'ordering': ['order'],
            },
        ),
    ]
