# Generated by Django 6.0.1 on 2026-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тақырып / Заголовок (опционально)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттама / Описание (опционально)')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Басты сурет / Главное изображение')),
                ('is_active', models.BooleanField(default=False, verbose_name='Белсенді / Активен')),
            ],
            options={
                'verbose_name': 'Басты экран (Hero)',
                'verbose_name_plural': 'Басты экрандар',
            },
        ),
        migrations.CreateModel(
            name='PrincipleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып / Заголовок')),
                ('description', models.TextField(verbose_name='Сипаттама / Описание')),
                ('icon', models.CharField(default='fas fa-star', help_text="FontAwesome class (e.g., 'fas fa-heart')", max_length=50, verbose_name='Иконка (FontAwesome)')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік нөмірі / Порядок')),
            ],
            options={
                'verbose_name': 'Қағида (Принцип)',
                'verbose_name_plural': 'Қағидалар (Принципы)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөні / ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Лауазымы / Должность')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік нөмірі / Порядок')),
            ],
            options={
                'verbose_name': 'Команда мүшесі',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='photoblock',
            options={'ordering': ['order'], 'verbose_name': 'Фото блок (Проект)', 'verbose_name_plural': 'Проекты (Слайдер)'},
        ),
    ]
