# Generated by Django 6.0.1 on 2026-02-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_heroblock_principleblock_teammember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Команда аты / Название команды')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_categories/', verbose_name='Сурет / Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік нөмірі / Порядок')),
            ],
            options={
                'verbose_name': 'Команда категориясы',
                'verbose_name_plural': 'Команда категориялары',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'Команда мүшесі', 'verbose_name_plural': 'Команда мүшелері'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Сипаттама / Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='content.teamcategory', verbose_name='Категория'),
        ),
    ]
