# Generated by Django 6.0.1 on 2026-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_teamcategory_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Сипаттама / Описание'),
        ),
    ]
