# Generated by Django 6.0.1 on 2026-02-01 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_teamcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып (Title)')),
                ('subtitle', models.CharField(help_text='Мысалы: #Мақала', max_length=100, verbose_name='Подзаголовок/Тег (Subtitle/Tag)')),
                ('short_description', models.TextField(help_text='Карточкада көрсетілетін қысқа мәтін', verbose_name='Қысқаша сипаттама (Short Description)')),
                ('card_image', models.ImageField(upload_to='news_images/', verbose_name='Карточка суреті (Card Image)')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Жарияланған күні (Publish Date)')),
                ('full_content', models.TextField(help_text='Мақаланың негізгі мәтіні', verbose_name='Толық мазмұны (Full Content)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жариялау (Is Published)')),
            ],
            options={
                'verbose_name': 'Жаңалық (News)',
                'verbose_name_plural': 'Жаңалықтар (News)',
                'ordering': ['-publish_date'],
            },
        ),
    ]
