# Generated by Django 6.0.1 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='image',
            field=models.URLField(verbose_name='Басты сурет URL / URL главного изображения'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='card_image',
            field=models.URLField(verbose_name='Карточка суреті URL (Card Image URL)'),
        ),
        migrations.AlterField(
            model_name='photoblock',
            name='image',
            field=models.URLField(verbose_name='Сурет URL / URL изображения'),
        ),
        migrations.AlterField(
            model_name='teamcategory',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Сурет URL / URL изображения'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.URLField(verbose_name='Фото URL'),
        ),
    ]
