# Generated by Django 6.0.1 on 2026-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_heroblock_image_alter_newsarticle_card_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1e7a45', max_length=20, verbose_name='Негізгі түс (Primary Color)')),
                ('accent_color', models.CharField(default='#2e90fa', max_length=20, verbose_name='Акцент түсі (Accent Color)')),
                ('footer_color', models.CharField(default='#0f3d23', max_length=20, verbose_name='Футер фоны (Footer Color)')),
            ],
            options={
                'verbose_name': 'Сайт настройкалары',
                'verbose_name_plural': 'Сайт настройкалары',
            },
        ),
    ]
