# Generated by Django 6.0.1 on 2026-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('font_family', models.CharField(blank=True, default='', max_length=100)),
                ('font_size', models.CharField(blank=True, default='', max_length=20)),
                ('font_weight', models.CharField(blank=True, default='', max_length=20)),
                ('bg_color', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Элемент стилі',
                'verbose_name_plural': 'Элемент стильдері',
            },
        ),
        migrations.CreateModel(
            name='SectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('bg_color', models.CharField(blank=True, default='', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Секция реті',
                'verbose_name_plural': 'Секция реті',
                'ordering': ['order'],
            },
        ),
    ]
