# Generated by Django 6.0.1 on 2026-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_elementstyle_sectionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstyle',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
