# Generated by Django 6.0.1 on 2026-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_elementstyle_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionorder',
            name='card_bg_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
