# Generated by Django 6.0.1 on 2026-05-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_sectionorder_card_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='principleblock',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Сурет URL'),
        ),
    ]
