# Generated by Django 6.0.1 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_principleblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тақырып')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('youtube_url', models.URLField(help_text='Мысалы: https://www.youtube.com/embed/aqz-KE-bpKQ', verbose_name='YouTube embed URL')),
                ('position', models.CharField(choices=[('featured', 'Басты видео (Featured)'), ('card', 'Карточка (Card)'), ('school', 'Мектеп видеосы (School)')], default='card', max_length=20, verbose_name='Позиция')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік нөмірі')),
            ],
            options={
                'verbose_name': 'Видео блок',
                'verbose_name_plural': 'Видео блоктар',
                'ordering': ['position', 'order'],
            },
        ),
    ]
